### ISSUE TITLE
load reference error

### ISSUE THREAD

**Issue by rsggsr** [LTLA/SingleR#109]
Hi,

My purpose would be using this fantastic tool to annotate my Seurat processed object unbiasedly. However, I encounter the first error when loading the ref (shown below). Is it a problem of proxy server? And could you kindly tell me how to fix it? Thanks!  

> hpca.se<-HumanPrimaryCellAtlasData()
No internet connection using 'localHub=TRUE'
Error in .updateHubDB(hub_bfc, .class, url, proxy, localHub) : 
  Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'

**Comment by dtm2451** [comment]
Looks like you may not have downloaded this (or any?) data from BiocHubs before.  Have you already tried running with `localHub = FALSE` as the error message suggests?  If so, what's the error then?

**Comment by LTLA** [comment]
First, report session information, it usually helps.

Second, I assume you were trying this on a machine with an internet connection. The notification provided by **ExperimentHub** is not well-worded, a better one would be:

```
No internet connection, using 'localHub=TRUE' instead
``` 

As @dtm2451 mentioned, if you haven't downloaded anything before, there's nothing in the local cache; hence the error about an invalid cache.

Connection issues can be difficult to resolve, depending on your firewall and location. Previous issues on this repo have discussed this (#72) and it seems to be just down to luck.

**Comment by rsggsr** [comment]
Hi,

I haven't download anything from BiocHubs (do I have to?). And the session info is shown below:

R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950  LC_CTYPE=Chinese (Traditional)_Taiwan.950   
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950 LC_NUMERIC=C                                
[5] LC_TIME=Chinese (Traditional)_Taiwan.950    

attached base packages:
 [1] splines   parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ExperimentHub_1.12.0        AnnotationHub_2.18.0        BiocFileCache_1.10.2        dbplyr_1.4.2               
 [5] monocle_2.14.0              DDRTree_0.1.5               irlba_2.3.3                 VGAM_1.1-2                 
 [9] scater_1.14.0               ggplot2_3.3.0               SingleCellExperiment_1.8.0  Matrix_1.2-18              
[13] dplyr_0.8.5                 Seurat_3.1.4                umap_0.2.5.0                SingleR_1.0.6              
[17] SummarizedExperiment_1.16.1 DelayedArray_0.12.3         BiocParallel_1.20.1         matrixStats_0.56.0         
[21] Biobase_2.46.0              GenomicRanges_1.38.0        GenomeInfoDb_1.22.1         IRanges_2.20.2             
[25] S4Vectors_0.24.4            BiocGenerics_0.32.0

**Comment by dtm2451** [comment]
You shouldn't have to do anything outside of running the call, except perhaps adding a `localHub=FALSE` argument, but (see below) that is actually not possible at the moment.

@LTLA, digging in, I just noticed that there is no way for a user to manually control the `localHub` setting for the `HumanPrimaryCellAtlasData` function.  So this is indeed an issue we need to address on our end.  I believe it should end up as `localHub = FALSE` by default for this user's use-case, or that we should allow user-control of ExperimentHub call arguments through `...` in the SingleR dataset calls.

**Comment by LTLA** [comment]
The error message is misleading. Our function is already trying to operate with `localHub=FALSE`, as is the default. That fails because there is no connection to the Bioconductor Hubs, in which case it falls back to `localHub=TRUE` in an effort to try to retrieve it locally (as discussed in #72). Obviously, that also fails because the user has never run this function before; there's nothing to retrieve locally because the content was never auto-downloaded in the first place.

As I mentioned before, the fundamental issue is that the user cannot establish a connection to the Bioconductor Hubs. This is probably related to intermittent availability of AWS S3 in certain locations. I don't really have a solution for this - I'm certainly not going to email the files to everyone, and if you asked me to host the files somewhere else, I would choose... AWS S3.

**Comment by rsggsr** [comment]
So...what's the recommended solutions? 

Could I just download the references from somewhere and put it in somewhere in my drive?

**Comment by dtm2451** [comment]
You will have to wait for now unfortunately:
- Per @LTLA 's 2nd comment above, we don't have a good alternative way of sharing the data. 
- We've reached out to the maintainer of AnnotationHub itself for thoughts on a long-term solution.

**Comment by rsggsr** [comment]
OK...I am looking forward to using it.

But still big thanks for you two for checking this issue and helping me even it still doesn't have solution.

**Comment by LTLA** [comment]
Do me a favor and see what these two commands do for you:

```r
curl::nslookup("dns.google.com", multiple = TRUE, error = FALSE, ipv4_only = TRUE)
## [1] "8.8.4.4" "8.8.8.8"
curl::nslookup("experimenthub.bioconductor.org", multiple = TRUE, error = FALSE, ipv4_only = TRUE)
## [1] "52.73.93.102"
```

**Comment by rsggsr** [comment]
Hi,

Please see below.

> curl::nslookup("dns.google.com", multiple = TRUE, error = FALSE, ipv4_only = TRUE)
[1] "146.112.61.106"
> curl::nslookup("experimenthub.bioconductor.org", multiple = TRUE, error = FALSE, ipv4_only = TRUE)
[1] "52.73.93.102"

**Comment by LTLA** [comment]
Excellent, thank you. Let's keep an eye on the issue in **curl** that I linked above.

**Comment by jeroen** [comment]
@rsggsr I am curious if this other method works in your case:

```r
pingr::is_online()
```

**Comment by rsggsr** [comment]
@jeroen nope....

> pingr::is_online()
[1] TRUE
> hpca.se <- HumanPrimaryCellAtlasData()
No internet connection using 'localHub=TRUE'
Error in .updateHubDB(hub_bfc, .class, url, proxy, localHub) : 
  Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
>

**Comment by LTLA** [comment]
Running `is_online()` won't change the behavior of `HumanPrimaryCellAtlasData()`. The point here is to determine whether we (or more specifically, the **ExperimentHub** functions underlying the `Data()` functions) have a better way of detecting connectivity in non-standard situations like yours. 

@lshep This is one option that is more robust than `curl::has_internet`. But looking for a specific connection to the ExperimentHub server seems more relevant for the purposes of these `Data()` getter functions; and that clause that I modified in Bioconductor/ExperimentHub#13 is only entered when `PROXY` is not set, so proxies shouldn't be a concern in any case.

**Comment by lshep** [comment]
So is it confirmed that using nslookup of "experimenthub.bioconductor.org"  will fix the issue?

**Comment by LTLA** [comment]
I assume so, see the [comment above](https://github.com/LTLA/SingleR/issues/109#issuecomment-614849035).

**Comment by lshep** [comment]
has_internet changed to nslookup in 1.13.8  pushed up this morning.  On github, should propagate to BiocManager::install after tomorrow's build report.  Cheers  (Also making this change in AnnotationHub)  -

**Comment by abysslover** [comment]
The above correction seemed not to be propagated. The workaround is as follows:
https://stackoverflow.com/questions/59796178/r-curlhas-internet-false-even-though-there-are-internet-connection

**Comment by LTLA** [comment]
Make sure you have ExperimentHub version 1.14.0.

**Comment by abysslover** [comment]
I found that if one updates the R version to 4.0.0, this error will not occur.
The problem is that installing R 4.0.0 is quite time-consuming because one needs to reinstall every thing from scratch. In addition, even with the above workaround, users will encounter another problems with most reference files while loading them as follows:
> .local(x, i, j, ...) : 'i' must be length 1

Hence, if one wants to try to use all the functionality of this package, one must upgrade R version to 4.0.0. Interestingly, HumanPrimaryCellAtlasData() worked regardless of version number changes.

I would appreciated it if @LTLA could provide reference files for each R version or make the reference files compatible for all the R versions. In that way, users can save their precious time, and reproduce their results if they cited this work with version number in their publication. **Disclaimer**: I lost quite amount of time to rebuild my R environment.

**Comment by LTLA** [comment]
> if @LTLA could provide reference files for each R version or make the reference files compatible for all the R versions.

All of the files _are_ available for every R version in which **SingleR** was supported on Bioconductor. All of the files _are_ compatible for all the aforementioned R versions. **SingleR** would not pass the checks on the Bioconductor build system otherwise. And the build system checks on all three major OS's, so I am confident that the package and all of its references work as advertised. For example, pulling the ImmGen dataset on an outdated version of R (3.6.3) on my cluster continues to work:

```r
library(SingleR)
packageVersion("SingleR")
## [1] ‘1.0.5’

se <- ImmGenData()
##   |======================================================================| 100%
## 
## snapshotDate(): 2019-10-22
## see ?SingleR and browseVignettes('SingleR') for documentation
## downloading 1 resources
## retrieving 1 resource
##   |======================================================================| 100%
## 
## loading from cache
## see ?SingleR and browseVignettes('SingleR') for documentation
## downloading 1 resources
## retrieving 1 resource
##   |======================================================================| 100%
## 
## loading from cache

se
## class: SummarizedExperiment
## dim: 22134 830
## metadata(0):
## assays(1): logcounts
## rownames(22134): Zglp1 Vmn2r65 ... Tiparp Kdm1a
## rowData names(0):
## colnames(830):
##   GSM1136119_EA07068_260297_MOGENE-1_0-ST-V1_MF.11C-11B+.LU_1.CEL
##   GSM1136120_EA07068_260298_MOGENE-1_0-ST-V1_MF.11C-11B+.LU_2.CEL ...
##   GSM920654_EA07068_201214_MOGENE-1_0-ST-V1_TGD.VG4+24ALO.E17.TH_1.CEL
##   GSM920655_EA07068_201215_MOGENE-1_0-ST-V1_TGD.VG4+24ALO.E17.TH_2.CEL
## colData names(2): label.main label.fine
```

So, let's be clear: the issue is _not_ with the **SingleR** package or its references. If you would like to point fingers, perhaps you would be better served by first examining your own network connection.

**Comment by abysslover** [comment]
Yes. I have checked my internet connection. Since curl::has_internet() returned false, I applied the workaround. Then, I was able to download all the reference files. However, the version mismatch finally caused the error I reported above.
> .local(x, i, j, ...) : 'i' must be length 1

I have upgraded all the other packages in R. 3.6.5, BiocManager::valid() reported nothing. In that environment, except for HumanPrimaryCellAtlasData(), and another database (I forgot the name), all the other databases complained with the above error.

I just inform you my specific case. The only way to utilize the full functionality was to rebuild all the environment in R 4.0.0.
