### ISSUE TITLE
Annotating with Paul reference

### ISSUE THREAD

**Issue by atflores** [LTLA/SingleR#116]
Hello, I'm attempting to annotate my data with the Paul et al. (2015) dataset from the scRNAseq package. I tried following a similar code as used for the MuraroPancreasData() reference dataset, e.g.

paul <- PaulHSCData()
paul <- paul[,!is.na(paul$label)]
paul <- logNormCounts(paul)
sce.paul <- SingleR(test=sce, ref=paul, labels=paul$label, de.method="wilcox")
Error in .setup_groups(groups, x, restrict = restrict, exclude = exclude) : 
  need at least two unique levels in 'groups'

But after the Error, I inspected the paul dataset and noted it didn't have a column that annotated the cells (e.g. functioned as paul$label).

 Is there an alternative way to set up the Paul reference so I may use it as my reference dataset?

Many thanks-

**Comment by dtm2451** [comment]
Hi @atflores,

Without looking at the PaulHSCData() myself, I'd expect, as you seem to, that the reason that you are getting this error is because the cell type labels are stored in that dataset in a different metadata slot than 'label'.

AFAIK, all the datasets in scRNAseq have some sort of known/called cell type information, but the name of the particular slot containing that information is not standardized.

I recommend poking around the other metadata slots to see if another one holds the proper info.

-Dan

**Comment by j-andrews7** [comment]
Yes, for that dataset you likely want `paul$Batch_desc`.

**Comment by atflores** [comment]
I see. It had to do with applying paul[,!is.na(paul$label)] on a slot that doesn't exist it and then inspecting the resultant empty object. Thanks!
