### ISSUE TITLE
Having issues with normalization for Heatmap

### ISSUE THREAD

**Issue by ncborcherding** [LTLA/SingleR#130]
New version of rfast returns the row order for rowMins and rowMaxs functions, so the normalization step is dividing by integers instead of scores. Was able to fix the issue by:

` # Normalize the scores between [0, 1] and cube to create more separation.

    if (normalize) {

        if (ncol(scores) > 1L) {

            mmax <- rowMaxs(scores, na.rm = TRUE, **values = TRUE**)

            mmin <- rowMins(scores, na.rm = TRUE, **values = TRUE**)

            scores <- (scores-mmin)/pmax(mmax-mmin, 1e-8)

            scores <- scores^3

        } else {

            warning("disabling normalization with only one label in ", scores.title)
        }

    }`

**Comment by LTLA** [comment]
I'm don't know what you mean, we don't use **rfast** for anything here.

**Comment by dtm2451** [comment]
Can you send an example of the issue you are seeing? With all packages up to date on my system, I see no issues with the `plotScoreHeatmap()` normalization, and the `rowMaxs()` and `rowMins()` functions used here are from `DelayedArray`, not `rfast`.

I suspect that your issue is from something else, but you haven't really described the issue you are seeing itself.  Can you send a more specific description of the issue as well as session info and ideally some some of minimal reproducible example?

**Comment by ncborcherding** [comment]
[CellTypes_complex2_ex1.pdf](https://github.com/LTLA/SingleR/files/4770784/CellTypes_complex2_ex1.pdf)

Here is an example of the heatmaps I was making. I think something must have gotten screwed up with my imports of rowMaxs and rowMins from `DelayedArray` - reinstalled and had no issues now.
