### ISSUE TITLE
The question for SingleR on Seurat

### ISSUE THREAD

**Issue by satellite119** [LTLA/SingleR#132]
Hi, I encountered a question when I used SinlgeR for cluster annotation from the Seurat data. 
<img width="709" alt="Screen Shot 2020-06-13 at 20 51 12" src="https://user-images.githubusercontent.com/31598126/84582939-33a10600-adb8-11ea-88a8-5f26714c11cd.png">

I use ImmGenData as Reference data and I take Cluster0 from Seurat data. My goal is to identify the cell type for Cluster0. But I got the results like this:

<img width="709" alt="Screen Shot 2020-06-13 at 20 51 21" src="https://user-images.githubusercontent.com/31598126/84582961-a611e600-adb8-11ea-9483-e49575c37d60.png">

Could you share me with some R codes or advices?
Thanks

**Comment by LTLA** [comment]
I usually follow a multi-step procedure to solve such problems.

1. Breathe in deeply.
2. Breathe out.
3. Relax.
4. Read the error message.
5. Fix your code and re-run it.
6. Repeat until the problem is solved.

In your case, the error message is pretty clear. The number of labels must be equal to the number of cells. How many labels did you pass to `labels=`? How many cells do you have in `ref`?

**Comment by dtm2451** [comment]
Specifically, the labels metadata options for `ImmGenData()` are `label.main`, `label.fine`, and `label.ont`.

You have simply given `labels = MouseDB$label`, but you need to provide `MouseDB$label.main` or one of the others.

**Comment by satellite119** [comment]
I have run SingleR successfully for my Seurat results by using ImmGenData as Reference.  Now I am trying to use a public single-cell reference from scRNAseq following the Tutorial. These are my commands:

MouseHPSC2<-GrunHSCData()
MouseHPSC2<-MouseHPSC2[,!is.na(MouseHPSC2$label)]
MouseHPSC2<-logNormCounts(MouseHPSC2)
C0.sce<-C0.sce[,colSums(counts(C0.sce))>0]
pred.C0<-SingleR(test=C0.sce,ref=MouseHPSC2,labels=MouseHPSC2$label,de.method = "wilcox")
 
The error is "no common genes between 'test' and 'ref' ". But when I use ImmGenData as Reference, it works fine and returns correct results. What could be the reason and how to fix it?
Thanks

**Comment by friedue** [comment]
You need to make sure that the feature names match in the two objects you're comparing, i.e. make sure that, for example, `rownames(C0.sce)` and `rownames(MouseHPSC2)` have to be in same format.

**Comment by j-andrews7** [comment]
The reason is that there are no common genes between your test and reference datasets. 

See `rownames(MouseHPSC2)` for how the features are named in the `GrunHSCData` set by default. Not sure what format it even is, to be honest. But you can get the Ensembl IDs for them instead by setting `ensembl = TRUE` when requesting the data, e.g. `GrunHSCData(ensembl = TRUE)`. These IDs are much easier to match, and you can get them for your own test dataset using AnnotationHub, as performed by the internal `scRNAseq` functions show [here](https://github.com/LTLA/scRNAseq/blob/master/R/convert_to_ensembl.R) that are easily adaptable to run on your object.

**Comment by LTLA** [comment]
Yes, `GrunHSCData()`'s row names are magical and mysterious, much like other datasets from that group at that point in time (see `GrunPancreasData()` and `MuraroPancreasData()`). If you want something truly weird, though, you must venture to `MacoskoRetinaData()`, where you get all-caps human gene symbols... for a mouse dataset.

Another benefit with Ensembl IDs is that, if you picked the wrong species, the comparison will fail immediately because there is no identifier overlap. In contrast, some gene symbols are shared between human and mouse annotations (e.g., some non-coding RNAs, predicted genes, other weird things). `SingleR()` will happily perform a nonsensical annotation based on that shared subset if your test is human and your reference is mouse or vice versa.

**Comment by j-andrews7** [comment]
I am assuming the answers here address your issue. Feel free to re-open if not.
