### ISSUE TITLE
Hierarchical labels for custom references

### ISSUE THREAD

**Issue by dstueckm** [LTLA/SingleR#138]
Hello, sorry if this has been asked before but I couldn't find a reference in the book or in any issues on github.

I've been using this package for a while now, and one of the features I really appreciate is the ability to use both fine.labels and broad.labels in many/all of the built in reference datasets. I've recently started creating custom references with pseudobulk aggregation, but I can only pass a single vector of labels to my reference object. Is there any way to generate my own fine/broad labels, or is this a possible future feature? Right now the only thing I can seem to do is create separate references for each set of labels and run the annotation twice.

As a side note/additional feature request, I'm interested in using broad and fine labels simultaneously to avoid low-confidence calls. This would essentially look like: if cell.fine.label.score < threshold, use cell.broad.label, otherwise keep cell.fine.label. I can implement this myself, but would be great to have it as part of a future release!

Thanks in advance

**Comment by dtm2451** [comment]
What you are noticing is actually a change in design, not a bug:

The original, pre-Bioconductor version of SingleR ran itself twice, by default. First it ran on the fine-labels, then on the main-labels (or maybe the other way around, but that makes no difference).  Results for both runs were then held inside the same, more-complicated, output object.

Now SingleR runs on just a single given set of labels per run. And we do not plan to change that. There is much better ease-of-use & reduction of often unnecessary computation this way.

BUT you do not need to create a separate reference as the labels do not need to be a part of the `ref` object. Thus, you can give use `ref = refX` for three different runs with labels = fine labels for one run, then labels = main labels for run two, and then maybe labels = some custom string vector for a third.

Because we do not plan to make SingleR know about multiple sets of labels per run, you would indeed need to implement your requested feature on your own.  But still, this seems simple to me because of our `pruneScores()` function, so here is some code that may help:

```
fine <- SingleR(..., labels = 'fine_labels')
main <- SingleR(..., labels = 'main_labels')

# check for passage of threshold
failed.cut <- pruneScores(fine)

# Start with fine labels
target.labels  <- fine$labels

# Replace failed fine labels with main labels.
target.labels[failed.cut] <- main$labels[failed.cut]
```

**Comment by dstueckm** [comment]
Great, thanks for the clarification!
