### ISSUE TITLE
plotDeltaDistribution not found

### ISSUE THREAD

**Issue by rbioinfo** [LTLA/SingleR#141]
Hello,
I am using SingleR 1.2.4 and when I try to use the plotDeltaDistribution function I get:

`Error in plotDeltaDistribution() : 
  could not find function "plotDeltaDistribution"`

Can you help me?
Thank you.

**Comment by j-andrews7** [comment]
That function is not in that version of the software. If you'd like to use it, you'll have to use the [development version](https://bioconductor.org/packages/devel/bioc/html/SingleR.html).

**Comment by rbioinfo** [comment]
Thank you. I have a question regarding the classic method to select genes. Is the default number of genes the best choice to avoid noise? I am trying higher values such as 500, 1000 or 2000 and I obtain different results.
Thank you.

**Comment by j-andrews7** [comment]
I'm actually not sure how the default value (`500 * (2/3) ^ log2(N)` where `N` is the number of unique labels) was determined. @LTLA may have some insight there. Increasing that value will contribute to increased noise, but I don't think there's a magic number that's going to be applicable across the board. How many genes are truly useful in differentiating labels depends very much on the labels in question. You can always provide your own markers for each comparison if you'd like.

**Comment by LTLA** [comment]
I also do not know what motivated that particular expression, I reproduced that faithfully from @dviraran's code. 

Qualitatively, the idea would be to decrease the number of genes per comparison as the number of pairwise comparisons increases with an increasing number of labels. So, even though the features you get per comparison decreases, you have more comparisons, which sort of balances out in the end. With a fixed number, there is the worst-case behavior of a quadratic increase in the number of genes (e.g., if every comparison yields a different set of DE genes), which would make it a bit pointless to do feature selection. This is probably most problematic for some of the **celldex** references with fine labels.

For single-cell references, speed was more important so I just set it to some small `de.n` when `de.method` is set to something other than the classic method. This also seems to do better, probably due to denoising.

In theory, it would be possible to learn the best `de.n` from single-cell references, e.g., by trying different numbers and seeing which one gives you the best precision/recall. I've hesitated to head down this path because of the risks of over-fitting on that particular training dataset, but it would be an interesting direction to explore for the next release.
