### ISSUE TITLE
  You're computing too large a percentage of total singular values, use a standard svd instead.

### ISSUE THREAD

**Issue by smk5g5** [LTLA/SingleR#161]
Hi,

When using aggregateReference on a custom reference data set I am getting the following warning the job has been running for last 24 hours though is there any way to speed it up?

Thanks!

Below is the code that is stuck!

`aggr_hanetal <- aggregateReference(han_etal,han_etal$celltype,power=0.5,BPPARAM=MulticoreParam()) saveRDS(aggr_hanetal, file = "/scratch1/fs1/allegra.petti/khan.saad/SingleR_kimgbm/Han_etal_tissue/han_etal_aggr.RDS")`

**Comment by LTLA** [comment]
If you want to talk speed, you'll need to give us much more detail than that.

- What is the size of `han_etal`? What is the matrix representation?
- How many levels are present in `celltype`?
- How many cores are you using? How much memory do you have?

For example, if you're on a mac, the process will just stall once you run out of memory.

**Comment by smk5g5** [comment]
This is the han_etal single cell experiment object : 

`class: SingleCellExperiment 
dim: 7528 572512 
metadata(0):
assays(2): counts logcounts
rownames(7528): AAAS AAED1 ... ZZEF1 ZZZ3
rowData names(0):
colnames(572512): Adult-Adipose1.1 Adult-Adipose1.2 ... Placenta1.9594 Placenta1.9595
colData names(3): cellname celltype sizeFactor
reducedDimNames(0):
altExpNames(0):`

There are `1289` celltypes present in this data.  I am using 248 gigs ram and 4 cores in LSF queue on a cluster.

**Comment by dtm2451** [comment]
Only 7528 cells shouldn't take an overnight calculation.  Looks like you answered all but one question, one which is a pretty important consideration here:

> What is the matrix representation?
How is the `logcounts` assay stored in the object?  Is it sparse?

**Comment by smk5g5** [comment]
Its not 7528 cells its 7528 genes btw.

**Comment by LTLA** [comment]
I don't really have any insights here. If we have a look at some mock timings:

```r
library(scuttle)
sce <- mockSCE(ngenes=8000, ncells=5000)
sce <- logNormCounts(sce)
sce$cell.type <- gl(5, 1000)

library(SingleR)
set.seed(1000)
system.time(aggregateReference(sce, sce$cell.type)))
##   user  system elapsed
## 32.066   0.550  32.771
```

So scaling that up by 100-fold indicates that it should take a bit under an hour. I'm already overestimating the average number of cells for each cell type, it would probably be even faster if there were more cell types with fewer cells each.

Maybe try getting some timings with a subset of the cell types. Each cell type is processed more-or-less independently anyway.

**Comment by dviraran** [comment]
My guess its a memory issue, so as @LTLA suggests it would be best to split the data and run the function on smaller subsets.

@LTLA as the number of cells is increasing and memory issues are bound to happen, it might be a good idea to add a function to merge such splits. I had such a function in my old version, where time and memory where a much bigger problem.

**Comment by LTLA** [comment]
Various comments, in no particular order:

- To be clear, `aggregateReference()` already processes the dataset one label at a time. The only additional memory usage comes from creating a subset containing the current label at each iteration; on average, I would expect this to be around 500-1000 cells here, which is negligible in terms of memory usage. In fact, the full 7k x 500k matrix would take up ~35 GB RAM, so absent other factors, there should still be plenty of RAM to do whatever needs to be done.
- Though a more scalable approach would have been to store the content in one or more `HDF5Matrix` objects, where data are stored on disk and pulled into memory on demand. Then you basically need no RAM at all.
- The merging strategy is pretty simple. Just run `aggregateReference()` on your subsets of choice and `cbind` the output together. This should be identical to the output of a single `aggregateReference()`  call as long as you set the same seed.
- The real problem with this function is that the parallelization is a bit inane; it operates on the rows rather than the labels. However, doing it the proper way is hard because we need to guarantee reproducibility of random operations in parallel sections. I need to go look up how to do that with **BiocParallel**, maybe it's not so bad.

**Comment by smk5g5** [comment]
Running the Prediction without doing aggregateReference gives the following error.

`Error: segfault from C stack overflow
Execution halted
Error: segfault from C stack overflow
Fatal error: error during cleanup

Error: segfault from C stack overflow
Fatal error: error during cleanup

Error: segfault from C stack overflow
Fatal error: error during cleanup`

This is the code that was used (for creating singleR reference object) after reading the matrix into a singlecellexperiment object.

`han_clust <- quickCluster(atlas_han,BPPARAM=MulticoreParam())
han_etal <- computeSumFactors(atlas_han, cluster=hanbrain_clust, min.mean=0.1,BPPARAM=MulticoreParam())
han_etal <- logNormCounts(han_etal,BPPARAM=MulticoreParam())
assayNames(han_etal)
saveRDS(han_etal, file = "Han_etal_tissue/brain_atlas_han.RDS")`

Using the above singlecellexperiment object for predicting the celltypes on another sce object produces the segfault errors above. Is there something I am doing wrong in creating the reference for singleR?

**Comment by LTLA** [comment]
I have no idea, I've never seen these errors before. Generally speaking this looks like a memory issue, but it's hard to pinpoint exactly where it's coming from. `SingleR()`'s implementation assumes that `test` is big and `ref` is relatively small, so it can take liberties with how `ref` is treated to achieve greater speed at the cost of memory usage.

So, you would be better served by getting `aggregateReference` to work. Certainly it shouldn't take a day.

**Comment by dtm2451** [comment]
Closing as I assume the lack of followup indicates a resolution.  Re-open if that is not the case!

**Comment by LTLA** [comment]
15c5adea27e742368c03f89455d32ae16a5426ac alters the aggregation so that parallelization is performed across labels, not rows. It also performs the PCA using only the top 1000 genes This should make `aggr.ref=TRUE` a _lot_ faster, though I still have to wrestle with the seeds...
