### ISSUE TITLE
The output of SingleR return de.genes, what does it mean?

### ISSUE THREAD

**Issue by lkqnaruto** [LTLA/SingleR#186]
I noticed that the metadata of the output of SingleR contains de.genes, I'm confused by what it means. Based on my limited understanding, genes in de.genes are those differentially expressed in the reference dataset for each label. SingleR identifies these genes first, which are differentially expressed for each label compared to others, and then use theses genes to calculate the Spearmans's correlation for each cell in the test dataset, and assign the label which has the highest  Spearmans's correlation score to the cell. If that is the case, what if those genes detected in the reference data does not exist in the test dataset, will it cause some prediction bias?

My second question is in the chapter 4 of SingleR book, where it talks about how to perform diagnostic based on the marker genes as follows:

```
# Taking the first 20 reference markers that are the top empirical markers.
library(scran)
empirical.markers <- findMarkers(sceG, sceG$labels, direction="up")
m <- match(beta.markers, rownames(empirical.markers$beta))
m <- beta.markers[rank(m) <= 20]

library(scater)
plotHeatmap(sceG, order_columns_by="labels", features=m)
```

What's the difference between the genes from de.genes and genes from findMarkers? Why they are different?

**Comment by LTLA** [comment]
> If that is the case, what if those genes detected in the reference data does not exist in the test dataset, will it cause some prediction bias?

Short answer: **SingleR** will just fail and refuse to do any assignments. 

Long answer: `SingleR()` actually takes the intersection of genes present in both test and reference datasets, so the detected markers for each label are already restricted to those genes that are present in both datasets.

Even longer answer: In theory, it is possible to identify the markers first and then trim them down based on the available genes in the test dataset. However, this can cause problems if, e.g., none of the detected markers for a label are present in the test dataset. It's safer to either repeat the marker detection for the intersection of genes or throw an error.

> What's the difference between the genes from de.genes and genes from findMarkers? Why they are different?

`de.genes` contains markers derived from the reference dataset, as computed from `findMarkers()`. The `empirical.markers` are obtained from the test dataset. The aim is to only show the reference-derived markers that are _also_ DE in the test dataset, so as to make a more concise and useful heatmap; otherwise you end up using a lot of space showing genes that aren't very useful.

**Comment by lkqnaruto** [comment]
@LTLA Really appreciate the helpful response.
