### ISSUE TITLE
SingleR with Seurat Object

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [LTLA/SingleR#195]
Hello, 
I am using the follow code in order to annote my Seurat clusters:

`SingleR(GetAssayData(seu_fin, assay = "RNA", slot = "data"), clusters = Idents(seu_fin),ref = immgen,  labels =immgen$label.fine)
`
but I am getting the following error

```
Error in `rownames<-`(`*tmp*`, value = tolower(rownames(ref_data))) : 
  attempt to set 'rownames' on an object with no dimensions
```
I get the same error when I tried to convert my seurat object to single cells experiment object and then run the SingleR() on that object

Is there a way to deal with it?

**Comment by christoforos-dimitropoulos** [comment]
I also get this errore when I try to get my ref data

```
> immgen <- ImmGenData(ensembl=TRUE)
Error: 'R_user_dir' is not an exported object from 'namespace:tools'
```

**Comment by LTLA** [comment]
For the second error:  you'll need R 4.0 or higher, see the [NEWS](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html).

For the first error: I don't know. No **SingleR** function uses a `ref_data` variable. Nor does any **celldex** function, AFAICT.

**Comment by dadarenedo** [comment]
Hi, I have a question related to SingleR and Seurat objects. Which assay should I chose before converting the Seurat object to a SCE and performing the cells annotations with singleR? 

In my cases I am integrating two different samples to compare cell types between them, I am inclined to think I should use the RNA assay instead of the integrated Assay. Is there any more documentation about this?

Thanks!

**Comment by LTLA** [comment]
Use raw counts. You can also have a look at a related discussion at #98.
