### ISSUE TITLE
Does SingleR work with integrated cell atlas?

### ISSUE THREAD

**Issue by Chengwei94** [LTLA/SingleR#203]
Does singleR works well with a integrated cell atlas(example Seurat integrated) for reference. I would think that only those which returns a corrected matrix would be able to work, as that else the batch effect would disrupt the DEGs in the reference data.

**Comment by friedue** [comment]
What type of analysis did you have in mind? In principle, you can feed scRNA-seq data with labels into SingleR, yes.

**Comment by Chengwei94** [comment]
I just want to annotate my dataset but the reference that I am using is a single cell dataset atlas that is merged using Seurat integration ( made of 30+ different datasets )

**Comment by LTLA** [comment]
For any annotation pipeline, the key consideration is to ensure that you're doing like-for-like comparisons (insofar as that's possible). So if your reference data is of a certain "type", then your test data should also be of the same "type".

With SingleR, the definition of "type" is pretty loose. Because it only cares about ranks, any monotonic transformation of the original counts is accepted, so you could use counts in your test data and log-transformed (scale-normalized) values in your training data. However, you'd still need to ensure that the broad concept of "type" is consistent, e.g., you would see degradation in performance if you used full-length read count data as the test and UMI data in the reference.

So that brings us to the question; is Seurat's integrated data of the same "type" as your test data? Who knows, but I would guess, probably not. I'm not aware of any monotonicity guarantees from integration methods, which are free to apply any transformation to meet their ultimate goal (of merging populations together). The situation would be simpler if your test data was part of the integration itself, but if you have access to the reference's original counts, you might as well just use them directly.

If you really have nothing but their integrated data, then you could always just try and see if you get something sensible.
