### ISSUE TITLE
'rownames(test)' does not contain all genes used in 'trained'

### ISSUE THREAD

**Issue by kysbbubbu** [LTLA/SingleR#43]
Hello

I have a problem in applying new verision of SingleR

I want to know how to fix the following errors when executing "classifySingleR" function.

'rownames(test)' does not contain all genes used in 'trained'

I think that due to various sensitivity of detection between library prep modalities, it could be common problems to others

Thank you

**Comment by dviraran** [comment]
Can you please post this issue in https://github.com/LTLA/SingleR ?

Thanks,
Dvir

**Comment by dtm2451** [comment]
Hello,

To fix the issue, you will want to subset your `ref` dataset to only include genes which are in your `test` dataset.

Why you newly get this issue: 

- Previously, a line of code checked for and removed non-matching genes, but never made mention of having done so.
- In the new version, as you've noticed, we unlinked the reference-based learning `trainSingleR` from application of that learning to classification of samples `classifySingleR`.  The `trainSingleR` portion now does not see the `test` data at all, so matching genes composition is not checked and must be done manually.

This issue is a caveat to having `trainSingleR` and `classifySingleR` separated.  However, having to acknowledge and explicitly handle gene mismatches is probably better than just having the issue dealt with behind the scenes.

**Comment by LTLA** [comment]
Dan's got most of it. I'll just mention that the `SingleR()` command will automatically find the intersection of genes as it does have access to both the test and reference data at the same time. 

The separation of `trainSingleR()` and `classifySingleR()` enables greater efficiency when you're doing repeated searches to the same reference. However, this efficiency is only possible if you don't have to re-index the reference for every test dataset; and if the intersection of genes changes with each test dataset, then there is no efficiency boost provided by splitting the two functions.

The use of the two split functions is only really intended for relatively advanced users who need more efficiency and control at the cost of some convenience.
