### ISSUE TITLE
Label doesn't look right

### ISSUE THREAD

**Issue by GHAStVHenry** [LTLA/SingleR#51]
Howdy, can I get some input on some data I have please:

![image](https://user-images.githubusercontent.com/38675268/67347155-d691d080-f506-11e9-8925-f354f71e6425.png)

I'm having a few labels which confuse me a little. A good example is the ID to the far right of this heatmap. This data was run in cluster mode. The far right one after fine tuning get's the label LE... the SM correlation seems so strong though that it seems unlikely that LE is the correct assignment. Even on the left there are a bunch of clusters which look like it should maybe be Hillock, but is getting a LE assignment.

FYI... I am trying to use a human reference to ID a mouse target, so the human genes are filtered and converted to orthologous mouse genes. That with filtering only for shared genes only leaves me about 14K genes. I know this is really reduced... but the first label is convincing and it seems unconvincing.

Thanks!
Gervaise

**Comment by LTLA** [comment]
You should realize that the heatmap colors can be pretty misleading. By default, the scores for each cell are normalized so that the lowest score is 0 and the highest score is 1. This can cause problems; for example, the difference between SM and LM scores in the rightmost cell is less than 0.05, but the normalization makes the difference look a lot bigger.

The official reason for this normalization is to make it easier to look at differences across the heatmap. Otherwise, the heatmap would be dominated by differences in the magnitude of the score between cells, whereas we really care about the differences in the scores within cells. The unofficial reason is that the heatmap looks prettier.

A more realistic picture of the correlations is obtained by setting `normalize=FALSE`. Alternatively, you could have a look at the other diagnostics, see the vignette for more details.

**Comment by dtm2451** [comment]
I'd thought of adding an input for turning off the cubing in the normalization process.  I can add it if we want!

_______________________________
Daniel Bunis
He/Him/His
PhD Candidate, Burt & Sirota Labs
Biomedical Sciences Program
University of California, San Francisco
daniel.bunis@ucsf.edu
856-905-0499

________________________________

**Comment by LTLA** [comment]
Might as well, though I don't know that it would make all that much of a difference, because the most misleading effect is probably derived from the coercion to [0, 1].

**Comment by dviraran** [comment]
My daughter likes to say that you get what you get and you don't get upset...

Another way to go about it is to not use the cluster mode, which kind of ruins the whole idea. If you look at it cell by cell you can see easily if a cluster, or regions in a cluster are annotated to a similar cell type, which means that there is a signal there that suggest this cell type. If the cluster is a mess then, well, its probably just noise... if you are having hard time with the 'single' mode (too many cells, not enough genes, etc.) then you can use a very lenient clustering definition (high resolution in Seurat) and use this clustering for the annotation.

**Comment by GHAStVHenry** [comment]
@LTLA: Wow, yes the normalization/scaling really has a dramatic effect! I see now how close those correlates are, that after fine-tuning it may favor LE over SM.

@dviraran: As, you said, for high number of cells and low number of genes in this analysis, "single" mode is kinda all over the place... so yes, the heatmap above is using a super high resolution... there is a more intermediate (still very high), that the fine-tuned label can be confirmed with known markers, that I will use. I was just confused why fine-tuning (on the super high resolution) would jump the label to something else that looked so dramatically lower based on these scores. Turns out it was the normalizing/scaling exaggerating that difference.

Using a reference from an appropriate species works great in "single" mode, it just seems to not like it when I remove half the genes available, which I can understand why.

Thank you all!

**Comment by LTLA** [comment]
To conclude this:

- I have added some commentary in `?plotScoreHeatmap` about this.
- `plotScoreHeatmap` switches to a unidirectional color scale (white->blue) when `normalize=TRUE`, rather than the default (blue->yellow->red) that is used when `normalize=FALSE`.
- When `normalize=TRUE`, the color bar is not shown, as the absolute values make little sense.
